### PR TITLE
Location autocomplete

### PR DESCRIPTION
**Pull request by kinsaurralde**
Predicts locations for location searchbar and route start/end locations.

Also adds button to clear route from map.

### CODE REVIEW

**Comment by kinsaurralde** [comment]
When searching for a location, suggestions appear.
capture-1-online-video-cuttercom


Clear route buttons clears the start and end search bars and removes route from map.
Screenshot 2020-08-21 at 2 23 44 PM - Display 1

**Review by alsile — APPROVED** [review]
These are solid changes, great look as well! It would be cool (unrelated to this PR) if the number of covid cases on the route was a different color font and maybe bolded etc. to show that this number is the one that changes everytime you search. Also maybe it should be hidden when a route hasnt been made

**Review by panerorenn9541 — APPROVED** [review]

**Review by huzcn — COMMENTED** [review]
I noticed that screen is blurred immediately after the search. Is this a real issue or just because of the effects in the gif?

**Comment by kinsaurralde** [comment]
> I noticed that screen is blurred immediately after the search. Is this a real issue or just because of the effects in the gif?

I think it is lag when the map zooms in.

**Review by huzcn — APPROVED** [review]

**Review by v01dstar — APPROVED** [review]
LGTM

**Pull request merged**
