### PR TITLE
Route link to google maps

### PR DESCRIPTION
**Pull request by kinsaurralde**
* Get link to google maps with selected route
* Send email containing link
* Select travel mode
* Set start location to current location

### CODE REVIEW

**Comment by kinsaurralde** [comment]
Shows buttons for opening link and sending email. It will look different when #21 is merged.
Screenshot 2020-08-13 at 1 14 16 PM - Display 1

Send email with link. Link is clickable after email sent.
Screenshot 2020-08-13 at 1 14 31 PM - Display 1

**Review by panerorenn9541 — APPROVED** [review]

**Comment by panerorenn9541** [comment]
Looks good! I can make the travel modes UI use icons instead of the pull down bar after you merge this

**Review by huzcn — APPROVED** [review]
Nice feature! Please make sure it's fully tested on both the web and the mobile.
A few ideas to improve the UI:

1. Some roads have their own colors, and it's easily mixed and visually confusing with the routes. Maybe we should learn from how google map is designed, e.g. make the routes bolder.
2. Overlapped routes have weird overlapped colors. I suggest using one color to highlight the selected routes and grey the rest.

**Comment by kinsaurralde** [comment]
Alternate routes are now grey and new buttons are styled.

Screenshot 2020-08-14 at 10 17 29 AM - Display 1

**Review by alsile — APPROVED** [review]
I really like the grayed out alternate routes, very nice polished feel. I think the next step (for all of us) is improving button design.

**Review by v01dstar — APPROVED** [review]
LGTM

**Pull request merged**
