### PR TITLE
Highlight area

### PR DESCRIPTION
**Pull request by kinsaurralde**
* Zoom map into searched location
* Highlight boundary of searched location
* Gets boundary data from openstreetmap

### CODE REVIEW

**Comment by kinsaurralde** [comment]
Some examples of what boundaries look like at country, state, city level

Screenshot 2020-08-17 at 10 52 32 AM - Display 1

Screenshot 2020-08-17 at 10 25 02 AM - Display 1

Screenshot 2020-08-17 at 10 37 34 AM - Display 1

**Review by panerorenn9541 — APPROVED** [review]

**Review by alsile — APPROVED** [review]
thats weird that the county surrounds an entire chunk of land that doesn't belong to it and some of the water is included in that county, like the color its not too intrusive and makes it clear

**Review by huzcn — COMMENTED** [review]
Looks super nice! I'm wondering what will happen if users click to see the heatmap. Will the colors be overlapped?

**Review by v01dstar — APPROVED** [review]
LGTM

**Comment by kinsaurralde** [comment]
> Looks super nice! I'm wondering what will happen if users click to see the heatmap. Will the colors be overlapped?

I changed it to disable highlight when heatmap is enabled.

Screenshot 2020-08-19 at 10 56 56 AM - Display 1

**Review by huzcn — CHANGES_REQUESTED** [review]
A few more questions:
1. Can the location be unhighlighted after the search? It looks like google map does this with a cross icon beside the search bar.
2. I feel the red boundary in your early screenshots are better. Can you keep the same color setting for the boundaries when the heatmap is on? This also enables a smooth/natural transition between them.

**Comment by kinsaurralde** [comment]
> A few more questions:
> 
> 1. Can the location be unhighlighted after the search? It looks like google map does this with a cross icon beside the search bar.

Just added a button to clear the search

> 2. I feel the red boundary in your early screenshots are better. Can you keep the same color setting for the boundaries when the heatmap is on? This also enables a smooth/natural transition between them.

I changed the color to blue to make it more obvious the highlighting had nothing to do with heatmap. It stays the same color whether or not heatmap is on.
Screenshot 2020-08-19 at 12 49 02 PM - Display 1

**Review by huzcn — APPROVED** [review]
LGTM. Can you change the boundary line to be thiner and lighter? As long as the area difference is visible, it should be good enough.

**Pull request merged**
