### PR TITLE
Relative heat

### PR DESCRIPTION
**Pull request by panerorenn9541**
- When relative heat is turned on, the heat map will show heat based on the areas that are on the screen (it will show compared to places that are visible)
- When relative heat is turned off, the heat map will show heat relative to the entire world

### CODE REVIEW

**Comment by panerorenn9541** [comment]
image

Relative heat button in drop down menu

**Comment by panerorenn9541** [comment]
image

Heat map when relative heat is turned off ^

image

Heat map when relative heat is turned on ^

**Comment by panerorenn9541** [comment]
image

Relative heat off ^

image

Relative heat on ^

**Review by alsile — APPROVED** [review]
This is a super cool feature, I think it would be more convenient for users to be able to turn this on while they're viewing the map (versus having to goto settings). Additionally, some explaination of the feature to the user (by hovering over the name of it or a ? mark icon next to it to explain it for example), would help users. Although users might be able to infer what relative heat means, it's way more clear to me (for example) of its function after reading your PR comment

**Review by kinsaurralde — APPROVED** [review]

**Review by huzcn — APPROVED** [review]
Nice improvement!

It would be best to change the button to a sliding bar so that users can choose the granularity of contrast. If you are really against this or it's technically difficult, I would suggest turning on the button by default so users can always see better contrast at first glance.

**Review by v01dstar — APPROVED** [review]
LGTM

**Pull request merged**
