### PR TITLE
Update video ui

### PR DESCRIPTION
**Pull request by alsile**
These changes add the following:
- update UI for video player buttons (no longer cover YouTube player buttons)
- update video search to always return video in the following way:
    - if the regular search doesn't return a video, increase the radius ten fold, 
    - if the regular search and max location radius still doesn't return, regular search without location and provide notification
- add alert if user goes through all found videos, telling them the next page
- add alert if user tries to goto the previous video and there aren't any
Potential undesired output:
draggable video player can hide controls if pulled to the button, I was unable to resolve this

Pictures of the new video controls and potential bug are shown below
Screenshot 2020-08-23 at 3 54 44 PM
Screenshot 2020-08-23 at 3 54 27 PM

Buttons look like this after style fix
Screenshot 2020-08-24 at 1 55 08 PM

### CODE REVIEW

**Review by kinsaurralde — APPROVED** [review]
The video buttons look different for me

Screenshot 2020-08-24 at 9 03 12 AM - Display 1

**Review by panerorenn9541 — APPROVED** [review]

**Comment by alsile** [comment]
> The video buttons look different for me
> 
> Screenshot 2020-08-24 at 9 03 12 AM - Display 1

Yeah fixing the style from lint forced me to change the buttons style, I assumed it wouldn't change the look it did, I fixed this, check the last picture in the PR

**Review by huzcn — APPROVED** [review]
Great work! It's fine to me that the button is not visible when dragged to the bottom.

**Comment by alsile** [comment]
I'm unable to get this to pass lint test, any ideas? I have tried manually shortening lines and running "make pretty", neither fixed

**Comment by kinsaurralde** [comment]
> I'm unable to get this to pass lint test, any ideas? I have tried manually shortening lines and running "make pretty", neither fixed

I dont know why this isnt passing either. I ran it locally and there were no problems.

**Review by v01dstar — APPROVED** [review]
LGTM

**Comment by huzcn** [comment]
I'm examining all the PRs, and wondering why this PR includes so many unrelated changes, which had already been merged to master branch before this PR. I guess there may be some merge conflict incorrectly resolved.

**Comment by alsile** [comment]
@huzcn yes, i think i merged instead of rebase or something like that. Most of the commits are from kyle and noe.

**Comment by huzcn** [comment]
Got it. Thanks for the clarification 👍

**Pull request merged**
