### PR TITLE
Directions UI changes

### PR DESCRIPTION
**Pull request by panerorenn9541**
- Change travel modes from drop down menu to three buttons
- Change so that when a new travel mode is selected, the route is automatically updated, without the user needing to press the search button again
- From Kyle: improve speed of Covid-19 stats loading
- Relative heat is initially on
- Remove button to set starting location to current location. Instead, make this happen initially

### CODE REVIEW

**Comment by panerorenn9541** [comment]
image

Travel modes button on top of directions drop down menu. Current location automatically entered as starting point

**Comment by panerorenn9541** [comment]
image

image

Button colors change and route changes when different mode is selected

**Review by alsile — APPROVED** [review]
Nice, the buttons look really nice!
Some thoughts: 
- keeping the button in case the user goes far away and wants to recenter
- what happens if user doesnt want to give location, does the website break?

**Review by kinsaurralde — APPROVED** [review]

**Review by huzcn — APPROVED** [review]
Nice!

**Pull request merged**
