### PR TITLE
Improve UI

### PR DESCRIPTION
**Pull request by panerorenn9541**
- Remove buttons from top, including: map/satellite, lat/lng, toggle heat map, heat selector, full screen, go to my location, show videos
- Move stats to top right of screen
- Add my location icon to bottom right of screen
- Add top navigation with search bar, video icon, and menu icon
- Add menu with stats toggle
- Menu also contains heat map and directions drop downs

### CODE REVIEW

**Comment by panerorenn9541** [comment]
image

Page appears like this initially

**Comment by panerorenn9541** [comment]
image

When menu is opened

**Comment by panerorenn9541** [comment]
image

When drop downs are opened. Next PR will be to make drop down and stats content look nicer

**Review by alsile — APPROVED** [review]

**Review by kinsaurralde — APPROVED** [review]

**Review by huzcn — APPROVED** [review]
Great UI improvement! You even designed our project LOGO!

**Pull request merged**
